Feature Statistics page and module
SalOne22/project-starship pull request #13
Opened 2023-10-14 15:26 UTC by em0nti

Implement base markup and styling for the Statistics page and module. Please review the code.

2023-10-14 15:47 UTC, SalOne22 requested changes
All good, but needs improvements in dark styles

2023-10-14 15:47 UTC, SalOne22 commented on src/modules/Statistics/Statistics.module.css
> +  border: rem(1) solid var(--mantine-color-blue-1);
Please add dark style with `light-dark()` function

2023-10-14 15:47 UTC, SalOne22 commented on src/modules/Statistics/Statistics.module.css
> +  color: var(--mantine-color-dark-6);
Here as well, add dark styles

2023-10-14 15:47 UTC, SalOne22 commented on src/modules/Statistics/Statistics.module.css
> +  color: var(--mantine-color-dark-6);
Write dark style

2023-10-14 15:48 UTC, SalOne22 commented
And please run prettier on your files

2023-10-15 10:36 UTC, em0nti commented on src/modules/Statistics/Statistics.module.css
> +  color: var(--mantine-color-dark-6);
Done

2023-10-15 10:40 UTC, em0nti commented on src/modules/Statistics/Statistics.module.css
> +  border: rem(1) solid var(--mantine-color-blue-1);
Done

2023-10-15 10:42 UTC, em0nti commented on src/modules/Statistics/Statistics.module.css
> +  color: var(--mantine-color-dark-6);
Done

2023-10-15 10:46 UTC, SalOne22 approved these changes

2023-10-15 10:46 UTC, merged

2023-10-15 10:57 UTC, em0nti commented
The `.prettierrc` configuration file in the project directory currently specifies only one rule. 
```json
{
  "singleQuote": true,
}

I've been using my own Prettier settings locally and this is most likely the problem