show reviews from db + translation
SalOne22/project-starship pull request #31
Opened 2023-10-16 17:54 UTC by zim89

2023-10-16 18:21 UTC, SalOne22 requested changes
Добавил поправки

2023-10-16 18:21 UTC, SalOne22 commented on src/modules/Reviews/components/ReviewCard.jsx
>          <Stack align="flex-start" justify="flex-start" gap={14}>
Здесь gap - 13px

2023-10-16 18:21 UTC, SalOne22 commented on src/modules/Reviews/Reviews.jsx
>  import '@mantine/carousel/styles.css';
Можно отсюда убрать этот импорт, он импортируется в App

2023-10-16 18:21 UTC, SalOne22 commented on src/modules/Reviews/Reviews.jsx
> +    dispatch(findAll());
Где обработка ошибок?

2023-10-16 18:21 UTC, SalOne22 commented on src/modules/Reviews/Reviews.jsx
> +          <Carousel
Этот слайдер должен прокручиваться автоматически

2023-10-16 18:21 UTC, SalOne22 commented on src/modules/Reviews/Reviews.jsx
> +            nextControlIcon={<ControlNext />}
Svg можно вынести в assets

2023-10-16 18:21 UTC, SalOne22 commented on src/modules/Reviews/Reviews.jsx
> +            slideGap={{ base: 0, xl: 24 }}
base: 0 выглядит странно на мобилке, добавь хотябы 8 пикселей

2023-10-17 06:28 UTC, zim89 commented
исправлены все замечания

2023-10-17 08:27 UTC, SalOne22 approved these changes
Все ок

2023-10-17 08:27 UTC, merged