Auth navigate
SalOne22/project-starship pull request #5
Opened 2023-10-13 20:36 UTC by TetianaOgni

2023-10-13 20:53 UTC, SalOne22 requested changes
Все окей, надо только вернуть проп тайпс обратно

2023-10-13 20:53 UTC, SalOne22 commented on package.json
> -    "prop-types": "^15.8.1",
Куда проп тайпс делся?
Проп тайпс это прямая зависимость, не дев

2023-10-13 20:53 UTC, SalOne22 commented on src/modules/Login/components/LoginForm.jsx
> +  // const handleSubmit = (event) => {
В релизной версии надо будет поубирать такие комментарии с кодом

2023-10-14 06:23 UTC, TetianaOgni commented on package.json
> -    "prop-types": "^15.8.1",
Вернула назад

2023-10-14 07:43 UTC, SalOne22 approved these changes
Все ок

2023-10-14 07:46 UTC, merged